// Package policy applies Sentinel DNS rules to generated Unbound fragments.
package policy

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Rule is a gateway-managed firewall rule (subset of gateway firewall_rules).
type Rule struct {
	RuleType string `json:"rule_type"`
	Target   string `json:"target"`
	Action   string `json:"action"`
	Value    string `json:"value,omitempty"`
	Enabled  bool   `json:"enabled"`
}

// Policy is the payload for POST /policy/apply and POST /rules/sync.
type Policy struct {
	OrgID     string   `json:"org_id"`
	NodeID    string   `json:"node_id"`
	Rules     []Rule   `json:"rules"`
	Upstreams []string `json:"upstreams"`
}

// Writer generates Unbound conf.d fragments under dir.
type Writer struct {
	Dir string
}

// Apply writes blocklist, allowlist, rewrites, and upstreams fragments.
func (w *Writer) Apply(p Policy) error {
	if err := os.MkdirAll(w.Dir, 0o755); err != nil {
		return err
	}
	blocks, allows, rewrites, upstreams := w.render(p)
	files := map[string]string{
		"blocklist.conf":  blocks,
		"allowlist.conf":  allows,
		"rewrites.conf":   rewrites,
		"upstreams.conf":  upstreams,
		"base.conf":       "# generated by erebrus-sentinel\n",
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(w.Dir, name), []byte(body), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func (w *Writer) render(p Policy) (blocks, allows, rewrites, upstreams string) {
	for _, r := range p.Rules {
		if !r.Enabled {
			continue
		}
		target := dnsZone(r.Target)
		switch r.Action {
		case "block":
			blocks += fmt.Sprintf("local-zone: %q always_nxdomain\n", target)
		case "allow":
			allows += fmt.Sprintf("# allow %s\n", target)
		case "rewrite":
			val := strings.TrimSpace(r.Value)
			if val == "" {
				continue
			}
			rewrites += fmt.Sprintf("local-zone: %q static\n", target)
			rewrites += fmt.Sprintf("local-data: %q 60 IN A %s\n", target, val)
		}
	}
	if len(p.Upstreams) > 0 {
		upstreams = "forward-zone:\n  name: \".\"\n  forward-tls-upstream: yes\n"
		for _, u := range p.Upstreams {
			addr := strings.TrimPrefix(strings.TrimPrefix(u, "tls://"), "https://")
			if strings.Contains(addr, "@") {
				upstreams += fmt.Sprintf("  forward-addr: %s\n", addr)
			} else {
				upstreams += fmt.Sprintf("  forward-addr: %s@853\n", addr)
			}
		}
	}
	return
}

func dnsZone(host string) string {
	host = strings.TrimSpace(strings.ToLower(host))
	host = strings.TrimSuffix(host, ".")
	return host + "."
}

// ParsePolicy decodes a policy JSON body.
func ParsePolicy(raw json.RawMessage) (Policy, error) {
	var p Policy
	if len(raw) == 0 {
		return p, nil
	}
	err := json.Unmarshal(raw, &p)
	return p, err
}