// Package edge implements the programmable public gateway (reverse proxy).
package edge

import (
	"fmt"
	"strings"

	"github.com/NetSepio/erebrus/internal/services"
)

// CaddyOptions configures generated Caddy config.
type CaddyOptions struct {
	PublicDomain   string
	WildcardDomain string
	HTTPPort       int
	HTTPSPort      int
	AutoTLS        bool
}

// GenerateCaddyfile renders a Caddyfile routing public hostnames to internal services.
func GenerateCaddyfile(svcs []services.Service, opt CaddyOptions) string {
	if opt.HTTPPort == 0 {
		opt.HTTPPort = 80
	}
	if opt.HTTPSPort == 0 {
		opt.HTTPSPort = 443
	}
	var b strings.Builder
	b.WriteString("# Generated by Erebrus — do not edit by hand\n")
	b.WriteString(fmt.Sprintf("{\n  auto_https %s\n}\n\n", autoHTTPS(opt.AutoTLS)))
	for _, s := range svcs {
		if !s.Public || s.PublicHost == "" {
			continue
		}
		target := s.InternalAddr
		if !strings.HasPrefix(target, "http") {
			target = "http://" + target
		}
		b.WriteString(s.PublicHost + " {\n")
		b.WriteString(fmt.Sprintf("  reverse_proxy %s\n", target))
		b.WriteString("}\n\n")
	}
	if opt.WildcardDomain != "" {
		b.WriteString(opt.WildcardDomain + " {\n")
		b.WriteString("  @svc host {labels.3}.{labels.2}.{labels.1}.{labels.0}\n")
		b.WriteString("  reverse_proxy @svc localhost:9081\n")
		b.WriteString("}\n\n")
	}
	return b.String()
}

func autoHTTPS(on bool) string {
	if on {
		return "on"
	}
	return "off"
}
