name: Build and Release Go Binary

on:
  push:
    branches:
      - node-features # Triggers only on pushes to the node-features branch
    tags:
      - 'v*' # Triggers when a new version tag (e.g., v1.0.0) is pushed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build Binary
        run: |
          go mod tidy
          go build -o erebrus

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: erebrus-binary
          path: erebrus

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: erebrus-binary

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: erebrus
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
